### ISSUE TITLE
Question about mask size

### ISSUE THREAD

**Issue by nicolebussola** [DIAGNijmegen/pathology-hooknet#10]
Hi!

I have a question regarding the size of the masks used as ground truth for the segmentation; in particular I was wondering why is the 
[mask size different from the input image size](https://github.com/DIAGNijmegen/pathology-hooknet/blob/0ffb53ea447bbfa6585c2d534f754c248b16d7a5/notebooks/user_config.yml#L15)?

Thank you

Nicole

**Comment by martvanrijthoven** [comment]
Dear Nicole,

The difference is due to the convolutions applied and the use of 'valid' padding instead of 'same' padding. With 'same' padding artificial pixels will be padded around the edges to make sure the input and output size remains the same size. However, with 'valid' padding border pixels will be lost. As a consequence, the final output is reduced to 70x70. HookNet uses 'valid' padding because 'same' padding can introduce border artifacts due to the artificial pixels.

I hope this answers your question. Please let me know if you have any other questions.

Best wishes,
Mart
