### ISSUE TITLE
Error regarding input images

### ISSUE THREAD

**Issue by Chinmaya6699** [DIAGNijmegen/pathology-hooknet#11]
Hey,
While trying to input images to the model, I am encountering a Huffman-encoding error. The error is as follows:
```
OpenSlideError                            Traceback (most recent call last)
Input In [20], in <cell line: 4>()
      4 with WholeSlideImage(image_path) as wsi:
      5     downsampling = wsi.get_downsampling_from_spacing(spacing_slide)
----> 6     slide = wsi.get_slide(spacing_slide)
      7 plt.title(f'{downsampling}')

Input In [10], in WholeSlideImage.get_slide(self, spacing)
     92 level = self.get_level_from_spacing(spacing)
     93 shape = self.shapes[level]
---> 94 return self.get_patch(0, 0, *shape, spacing, center=False)

Input In [10], in WholeSlideImage.get_patch(self, x, y, width, height, spacing, center, relative)
    150 if center:
    151     x, y = x - downsampling * (width // 2), y - downsampling * (height // 2)
--> 153 return self._backend.get_patch(x, y, width, height, level)

File ~/.conda/envs/tiger/lib/python3.8/site-packages/wholeslidedata/accessories/openslide/backend.py:20, in OpenSlideWholeSlideImageBackend.get_patch(self, x, y, width, height, level)
     15 def get_patch(
     16     self, x: int, y: int, width: int, height: int, level: int
     17 ) -> np.ndarray:
     19     return np.array(
---> 20         super().read_region((int(x), int(y)), int(level), (int(width), int(height)))
     21     )[:, :, :3]

File ~/.conda/envs/tiger/lib/python3.8/site-packages/openslide/__init__.py:228, in OpenSlide.read_region(self, location, level, size)
    218 def read_region(self, location, level, size):
    219     """Return a PIL.Image containing the contents of the region.
    220 
    221     location: (x, y) tuple giving the top left pixel in the level 0
   (...)
    226     Unlike in the C interface, the image data returned by this
    227     function is not premultiplied."""
--> 228     return lowlevel.read_region(self._osr, location[0], location[1],
    229             level, size[0], size[1])

File ~/.conda/envs/tiger/lib/python3.8/site-packages/openslide/lowlevel.py:214, in read_region(slide, x, y, level, w, h)
    212     return PIL.Image.new('RGBA', (w, h))
    213 buf = (w * h * c_uint32)()
--> 214 _read_region(slide, buf, x, y, level, w, h)
    215 return _load_image(buf, (w, h))

File ~/.conda/envs/tiger/lib/python3.8/site-packages/openslide/lowlevel.py:151, in _check_error(result, func, args)
    149 err = get_error(args[0])
    150 if err is not None:
--> 151     raise OpenSlideError(err)
    152 return _check_string(result, func, args)

OpenSlideError: Huffman table 0x00 was not defined
````

I am not able to train HookNet on the Tiger Dataset due to this factor. Is there any fix?
I would also like to know if there is a way to input ROIs directly to the model, instead of a whole slide image.

**Comment by martvanrijthoven** [comment]
Dear Chinmaya Venkatesh,

The error that you get comes from the openslide library. I have not encountered this problem myself. Could you let me know on which OS you get this error, and which versions you are using of openslide and wholeslidedata?

Alternatively, you can use another backend instead of openslide. You can use the 'asap' and 'pyvips' in addition to the 'openslide' backend. For the other backends you will need to install the required software: [asap](https://computationalpathologygroup.github.io/ASAP/) or [pyvips](https://anaconda.org/conda-forge/pyvips)

There is also the possibility to train directly from the ROIs. We have released the pngs and mask-pngs with the tiger-dataset under the 'roi-level-annotations' subfolder on AWS. 

Best wishes,
Mart

**Comment by Chinmaya6699** [comment]
Hi Mart,
Thanks a lot for the quick response. I am using CentOS Linux release 7.9.2009. The versions of openslide and wholeslidedata are openslide-3.4.1 and the latest version of wholeslidedata(using `pip install wholeslidedata`).
Unfortunately 'asap' doesn't work on CentOS. 
Also, could you let me know how do I input the ROIs to the model? From the 'user_config.yml' file it appears as though only the 'tif' format of input is supported, while the ROIs are in png. I have the tiger-dataset downloaded.

**Comment by martvanrijthoven** [comment]
Dear Chinmaya Venkatesh,

Thank you for the information! I could reproduce your problem. I have opened an issue here:
https://github.com/openslide/openslide-python/issues/166

The wholeslidedata package is specifically designed for whole slide images and does not support the loading of PNGs. If you want to use the PNGs, you can load them into NumPy arrays and feed them to HookNet or you could use a Keras generator.

Best wishes,
Mart

**Comment by Chinmaya6699** [comment]
Looks like it is an OS issue on my end. If I am using the Keras Generator or feeding it via NumPy arrays, I would have to feed the data accordingly to `model.train_on_batch(x=x_batch, y=y_batch, return_dict=True)` where the shapes of x is `(2,batch_size,284,284,3)` and y is `(2,batch_size,70,70,3)`. Is that right?

**Comment by martvanrijthoven** [comment]
Dear Chinmaya Venkatesh,

Yes indeed. Please note that the input should be of type list (with inside NumPy arrays). This is because Keras expect a list when using multiple inputs/outputs. 
Furthermore, if you train with multiloss (i.e.,[loss weights](https://github.com/DIAGNijmegen/pathology-hooknet/blob/249f9b22558d7b1eee2647ef412c9b790c06cd18/hooknet/model.py#L60) != [1.0, 0.0]) you indeed give the two outputs as y. However, if you train with only the single loss ([loss weights](https://github.com/DIAGNijmegen/pathology-hooknet/blob/249f9b22558d7b1eee2647ef412c9b790c06cd18/hooknet/model.py#L60) == [1.0, 0.0]) you only have to give the target output (e.g., (batch_size,70,70,3))

Best wishes,
Mart
