### ISSUE TITLE
How to produce mask for Input 508,508 as output is different?

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [DIAGNijmegen/pathology-hooknet#15]
Hi,

Thanks for sharing your work. I find it very useful.
I understand you are using valid padding for convolution operations which is reducing your output shape to 294,294 in my case [508,508,3] image size. Can you please suggest on how to resize the output mask to match input shape. One way I can think of is to apply resize directly on the output or the other way is to apply conv2dTranspose to make the network learn to predict 588,588 mask and crop to 512,512 size.
Can you please help.

Thanks again.

**Comment by martvanrijthoven** [comment]
Dear Ajaz Ahmad,

Thank you for your interest in HookNet!

The output shape of HookNet for the input shape (284x284x3) is 70x70 (which I used in the paper). This is indeed due to valid padding. Please note that you can not use arbitrary input sizes due to pixel-wise alignment requirements. You can check which input shapes are valid with this script: https://github.com/DIAGNijmegen/pathology-hooknet/blob/dc518adab1fcb1d4c77ac889ead94f16c39d46d8/hooknet/utils.py#L18

The best way to deal with the difference between the input shape and output shape is to crop the output target mask. If you use the wholeslidedata package, this can be easily done by adding a sample callback to the config: e.g.:

https://github.com/DIAGNijmegen/pathology-hooknet/blob/dc518adab1fcb1d4c77ac889ead94f16c39d46d8/notebooks/user_config.yml#L17-L20


Please let me know if you have any further questions.

Best wishes,
