### ISSUE TITLE
Computational Resources

### ISSUE THREAD

**Issue by AyaAq** [DIAGNijmegen/pathology-hooknet#7]
Hi,

I am trying to train HookNet on my dateset. I have written a simple data-generator and ti seems to be working now. However, I keep running into an OOM (out of memory) error. I tried decreasing the batch size (1) , patch size (6, 6, 3), number of filters (2), but I keep getting this error. I was a little surprised because I am running it on a gpu with 175GB of memory and I am still running out of memory with theses minimal parameters. I am currently working on training the network on multiple gpus, but I wanted to ask if my situation is normal, or do you think something has been missed up in the code while I was working on the batch generator? also, can you give me an estimation of the required computational resources for training the network if possible? 

Thanks in advance!

**Comment by martvanrijthoven** [comment]
Hi AyaAq,

I am sorry to hear that you have troubles with OOM. Is this OOM on GPU or RAM? In my experiments i have used the following settings: 
 - batch_size=12, 
 - patch_size=(284x284x3), 
 - number_of_filters=64. 

I ran the experiments on a GPU with 11GB and about 20GB RAM. It is very weird if you would run out of GPU memory when using 175GB GPU memory, and I would say that this is not normal. The 20GB RAM is a bit high because I loaded a lot of patches in memory while training. You could definitely use less RAM if you don't have that resource.

I assume that using a patch size of (6,6,3) was probably just to debug the OOM error. But I want to mention here that you should be very careful using different patch sizes. The issue is that every feature map size should be 'even' before the pooling operation. With a (6,6,3) patch size you will probably get an error that the feature maps size will become below zero due to valid padding.
If you would use 284x284x3 for training and 1244x1244x3 for inference it will be fine. Other input sizes are possible but you will have to compute if the constraints are satisfied. Please see the paper for more details.

I would be happy to help you debug the OOM error as much as I can. Let me know what I can do for you.

**Comment by AyaAq** [comment]
Thank you for your detailed response. This was very helpful. Now I can tell it is the batch generator that might be causing this error somehow and focus on it. 

Thanks again,
Aya

**Comment by martvanrijthoven** [comment]
Sure, no problem.

Let me know if you have any further questions.

Kind regards,
Mart
